<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit10bffa25b415bef708a67fe8aef24854
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MESH\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MESH\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit10bffa25b415bef708a67fe8aef24854::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit10bffa25b415bef708a67fe8aef24854::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit10bffa25b415bef708a67fe8aef24854::$classMap;

        }, null, ClassLoader::class);
    }
}
